### ISSUE TITLE
quill-emoji.js changes body{background} - don't do this

### ISSUE THREAD

**Issue by oliveratgithub** [contentco/quill-emoji#10]
Please remove this from the CSS:
```css
body{background:#fff}
```
https://github.com/contentco/quill-emoji/blob/aa9f90d88acbdf7c9d66a2f1cf231bf855f4b07f/src/scss/core/_styles.scss#L4
